-- MySQL Script generated by MySQL Workbench
-- Mon Oct  2 21:39:25 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Customers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Customers` (
  `idCustomers` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `lastName` VARCHAR(45) NOT NULL,
  `birthDate` DATE NULL,
  `phoneNumber` VARCHAR(10) NULL,
  `email` VARCHAR(45) NULL,
  PRIMARY KEY (`idCustomers`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Table`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Tables` (
  `idTable` INT NOT NULL AUTO_INCREMENT,
  `status` VARCHAR(45) NOT NULL DEFAULT 'Free',
  `places` INT NOT NULL,
  PRIMARY KEY (`idTable`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Employees`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Employees` (
  `idEmployees` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `lastName` VARCHAR(45) NULL,
  `birthDate` DATE NULL,
  `phoneNumber` VARCHAR(10) NULL,
  `email` VARCHAR(45) NULL,
  `position` VARCHAR(45) NULL,
  `status` VARCHAR(45) NULL DEFAULT 'Active',
  PRIMARY KEY (`idEmployees`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Reservations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Reservations` (
  `idReservations` INT NOT NULL AUTO_INCREMENT,
  `date` DATETIME NULL,
  `idCustomer` INT NOT NULL,
  `idTable` INT NOT NULL,
  `idEmployees` INT NOT NULL,
  PRIMARY KEY (`idReservations`),
  INDEX `fk_Reservations_Customers_idx` (`idCustomer` ASC) VISIBLE,
  INDEX `fk_Reservations_Table1_idx` (`idTable` ASC) VISIBLE,
  INDEX `fk_Reservations_Employees1_idx` (`idEmployees` ASC) VISIBLE,
  CONSTRAINT `fk_Reservations_Customers`
    FOREIGN KEY (`idCustomer`)
    REFERENCES `mydb`.`Customers` (`idCustomers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Reservations_Table1`
    FOREIGN KEY (`idTable`)
    REFERENCES `mydb`.`Tables` (`idTable`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Reservations_Employees1`
    FOREIGN KEY (`idEmployees`)
    REFERENCES `mydb`.`Employees` (`idEmployees`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Orders` (
  `idOrder` INT NOT NULL AUTO_INCREMENT,
  `created` timestamp default current_timestamp,
  `status` VARCHAR(45) NULL DEFAULT 'Open',
  `idTable` INT NOT NULL,
  `idCustomers` INT NOT NULL,
  `idEmployees` INT NOT NULL,
  PRIMARY KEY (`idOrder`),
  INDEX `fk_Order_Table1_idx` (`idTable` ASC) VISIBLE,
  INDEX `fk_Order_Customers1_idx` (`idCustomers` ASC) VISIBLE,
  CONSTRAINT `fk_Order_Table1`
    FOREIGN KEY (`idTable`)
    REFERENCES `mydb`.`Tables` (`idTable`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Order_Customers1`
    FOREIGN KEY (`idCustomers`)
    REFERENCES `mydb`.`Customers` (`idCustomers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Order_Employees`
    FOREIGN KEY (`idEmployees`)
    REFERENCES `mydb`.`Employees` (`idEmployees`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Products` (
  `idProduct` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `price` DECIMAL NOT NULL,
  PRIMARY KEY (`idProduct`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`OrdersProducts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`OrdersProducts` (
  `idOrder` INT NOT NULL,
  `idProduct` INT NOT NULL,
  PRIMARY KEY (`idOrder`, `idProduct`),
  INDEX `fk_Order_has_Products_Products1_idx` (`idProduct` ASC) VISIBLE,
  INDEX `fk_Order_has_Products_Order1_idx` (`idOrder` ASC) VISIBLE,
  CONSTRAINT `fk_Order_has_Products_Order1`
    FOREIGN KEY (`idOrder`)
    REFERENCES `mydb`.`Orders` (`idOrder`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Order_has_Products_Products1`
    FOREIGN KEY (`idProduct`)
    REFERENCES `mydb`.`Products` (`idProduct`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
